spring:
  application:
    name: CaloriTrack
  profiles:
    active: secrets
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: TRACE
    com.secureuser.service.model.listener: DEBUG
server:
  port: 8080